### ISSUE TITLE
Using the TWS extension may confuse people that it is a Twine 1 story project 

### ISSUE THREAD

**Issue by greyelf** [wweather/ravel#1]
If a person has the Twine 1 application installed (and many people do) then the TWS file extension may/will be associated within their operating system to that application. Opening your TWS file using the Twine 1 application will result in the user seeing an error message because Twine 1's TWS file is a Python Pickle file whereas your TWS file is plain text.

I strongly suggest using some other file extension.

If your file is meant to represent a Twee text file then you may want to use file-name.twee

**Comment by wweather** [comment]
I suppose that's a fair concern.

**Comment by wweather** [comment]
Fixed.
