### ISSUE TITLE
ravel.exe closes immediately

### ISSUE THREAD

**Issue by Femssmoi** [wweather/ravel#3]
Hey, I'm pretty new to all of this, so please bear with me. 

I've managed to create a ravel.exe and also to open it via cmd, but it closes itself immediately. What am I doing wrong?

**Comment by wweather** [comment]
Ravel is a command-line tool. To use it, first open Command Prompt and navigate to your ravel folder. Then, you can run ravel without arguments to get basic help. Check readme.txt for details.
